### PR TITLE
Implement #2

### PR DESCRIPTION
**Pull request by vantezzen**
Implementing a way to easily start timers that take seconds, minutes or hours to complete.

The script will sum up all arguments and run a timer for that many seconds.

Examples:
```sh
bash timer 5min
bash timer 5hours
bash timer 5hours 6minutes
bash timer 1second
bash timer 2seconds
bash timer 5minutes 6hours # Units don't have to be in order
bash timer 5minutes 7minutes 8minutes # A unit can be used more than once => 20 minute timer
bash timer 5 # Script stays compatible with current syntax: If no unit is provided, it will fall back to minutes
bash timer 1hour 5 # This can be used to remove the unit whenever you want to add minutes
```

### CODE REVIEW

**Comment by Cazaimi** [comment]
@vantezzen , could you base this off of `develop`? I'll add the same to CONTRIBUTING.md .

**Comment by vantezzen** [comment]
Ok, changed the base to `develop`.

**Comment by Cazaimi** [comment]
@vantezzen looks good apart from the validation. Could you add that as well? Let me know once you, I’ll review and merge.

**Comment by vantezzen** [comment]
Ok, I have now added validation for minutes and seconds.

**Review by Cazaimi — APPROVED** [review]

**Pull request merged**
